trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: PowerShell@2
    inputs:
      pwsh: true
      targetType: "inline"
      script: Write-Host "Hello World"
    env:
      # renovate: datasource=nextcloud depName=user_oidc
      USER_OIDC_VERSION: 7.3.0
